# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  description: "A logging implementation for `log` which is configured via an environment variable."
  homepage: "https://docs.rs/env_logger"
  topics: "rust logging"
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: false
  default_branch: main

  # Preference: people do clean commits
  allow_merge_commit: true
  # Backup in case we need to clean up commits
  allow_squash_merge: true
  # Not really needed
  allow_rebase_merge: false

  allow_auto_merge: true
  delete_branch_on_merge: true

  squash_merge_commit_title: "PR_TITLE"
  squash_merge_commit_message: "PR_BODY"
  merge_commit_message: "PR_BODY"

branches:
  - name: main
    protection:
      required_pull_request_reviews: null
      required_conversation_resolution: true
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: false
        contexts: ["CI", "Lint Commits", "Spell Check with Typos"]
      enforce_admins: false
      restrictions: null
